### ISSUE TITLE
notification + spyglass appear stuck

### ISSUE THREAD

**Issue by itspangler** [bplmaps/atlascope-v2#34]
encountered this bug while stress testing @garrettdashnelson's layer handling updates. it appeared for me when i jumped to a place with no historic layers available, and then quickly returned to the map. both the notifications and the spyglass got stuck and i couldn't clear it without a hard refresh:

![Screenshot 2023-02-17 at 9 59 40 AM](https://user-images.githubusercontent.com/39773984/219689996-74905922-c0db-44fa-bc4c-1ab991d1a1c4.png)

having trouble reproducing it locally or on production, but want to put on your radars in case you encounter it as well.

**Comment by emilyrbowe** [comment]
This seems similar enough to what @itspangler noticed above, but if you move to a place that has different historic layers available while you have one of the layer menus open, the layer menu gets stuck and won't close. 
![image](https://github.com/bplmaps/atlascope-v2/assets/7975988/4df6d69a-1889-4184-ab7e-320685b046d8)
