### ISSUE TITLE
V2 not working on Chromebook browser

### ISSUE THREAD

**Issue by emilyrbowe** [bplmaps/atlascope-v2#35]
Need to verify version of Chromebook OS that was used, but website was not loading. Atlascope V1 worked.

**Comment by garrettdashnelson** [comment]
@emilyrbowe Did we ever figure this out? Was it just IP address blocking on the Chromebooks?

**Comment by emilyrbowe** [comment]
Never heard back — I think we might be able to ignore for now.

**Comment by garrettdashnelson** [comment]
Flagging as stale and closing.

**Comment by emilyrbowe** [comment]
Never heard more from Lynn/Michelle, so I think we can call this closed for right now.
